// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * RFC 9457 problem details, plus a stable `code` clients can branch on.
 *
 * See `docs/API.md`.
 */
export type Problem = {
    /**
     * Stable and machine-readable. Clients branch on this, never on `detail`.
     */
    code: string;
    /**
     * Prose. May change between releases.
     */
    detail: string;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    status: number;
    title: string;
    type: string;
};

/**
 * Build identity of the running service.
 */
export type Version = {
    /**
     * Git SHA the binary was built from, or `dev` for a local build.
     */
    revision: string;
    /**
     * Crate version.
     */
    version: string;
};

export type VersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type VersionResponses = {
    /**
     * Build identity
     */
    200: Version;
};

export type VersionResponse = VersionResponses[keyof VersionResponses];
