// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * RFC 9457 problem details, plus a stable `code` clients can branch on.
 *
 * See `docs/API.md`.
 */
export const zProblem = z.object({
    code: z.string(),
    detail: z.string(),
    errors: z.record(z.string(), z.array(z.string())).nullish(),
    status: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    title: z.string(),
    type: z.string()
});

/**
 * Build identity of the running service.
 */
export const zVersion = z.object({
    revision: z.string(),
    version: z.string()
});

/**
 * Build identity
 */
export const zVersionResponse = zVersion;
