#ENC[AES256_GCM,data:MlVeJfe+LNeuzwj1epH8JusjuIzi6aNSyx3Z0iLnKabyzAGXzot43ZMFErHTPMPa+9jcrqIDDnEq+bnjCw3f83vCgoelmhlgdMnZlyNgvQ==,iv:m1C9DGGqhUaIA5RCmByYrNf4qtQyZD+WzUo9f61111s=,tag:UjYyui7PKPlWIG1wBcHJOA==,type:comment]
#ENC[AES256_GCM,data:kA2mY3B0tzQlFBu33xeK3YqIQR4oiVK2q9og5FRRVksRKKnhDIzMPq/EqNlCpuSLtb/UoplFn2RCZjbkNccgJJYFnGrAsDqHB2g=,iv:jjjKR5eGar9hpFcyNTUSIEn+0spQjF02PJhi7Lcn0Wk=,tag:uz9DeL0Klz9tdw/R4rUpjw==,type:comment]
#ENC[AES256_GCM,data:sQ4r0vkvwGtPrfdNCl9GIshD2ekp7GG4O6j8kVmjEHHbbQXnd5bo4SqTgQ6adn8AdIrlroTR2NdNXaErwV9kt6hSce20G7/ehw==,iv:5jbWbd+Hpsjm3NT3kqadg7Aci9gHNJLPpUbWBmZlELA=,tag:U9vhkymVqpy1odYpbJ5WkA==,type:comment]
secrets:
    garage:
        rpcSecret: ENC[AES256_GCM,data:H7eijNCP755K+dX6HdKEMwO43caT1pV3Cnvhck+/WAaWXRv4wflI3zJC9wi7fpQMDCQBzj5lvbVsApfZXCOJPQ==,iv:N74HuB1t5y0sj0Kns7TvCsQukKBDtc5Rw/US9Hr+OKU=,tag:N0EM4XQmkMrsQkG6pGYuZQ==,type:str]
        adminToken: ENC[AES256_GCM,data:m2ctDprOCeyfkF0AdgorM4jEljzeVC1tXv2qhpJpETeRHI3L8Aq1s+TF7+pmQNnfN/IvrXBvXOY+1r6/f91p+w==,iv:LiFk4pGjWWgPe/VJNCTk6yYjCuzzacHLY3it/xV2Suw=,tag:k3oEIcKdmcd6Ffc4zPcHOQ==,type:str]
        accessKeyId: ENC[AES256_GCM,data:wp1Ynp1bMSzvM58DlcaVaZHwyi/2xZ55WFs=,iv:JIwSk4hcN47wDFBiYfXhjw0uAP0nIjNUMV9eodDDGEw=,tag:NterlHiKO0IA1Q8j18d3Iw==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:2E6cvckgAEUuKoSa4WhR3utfP5KgC2+a4TJ0m6K8yoiitIPAEFa1Iym+x89IsBtudkYWepnX3xTBzFaRu2h2XA==,iv:MzpTvg8UZpCuIDeum1H+/fiy23hPfnQBHOiUhrWZjcQ=,tag:m0kP1Y0qtcOHLyU4c4wb8Q==,type:str]
    meilisearch:
        masterKey: ENC[AES256_GCM,data:UmKKou9YgSVzKAmnHbF61WyBLF8Mlfc61Like6gpzRfky6MCsNZ8GCU2WYC/I46MvlJLX2HsCz+CGo3wgWJK5A==,iv:p+q8kwMnHGPnNzFMYaBd3YG81F5wWrAgznNWQpNDDL8=,tag:RQB0O6O+M/w/sOPmjSFgUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYXhJSjVqNFNiaG5uVHJ0
            ZnlIejFYZjdYbG5IandmUTJOSjJjTFpyMVU4CjhtSWtKdXBRVUp2SWQxOEIxSFhY
            UkNuTEhPRkRDSGFhR0FkMHMzU1hHTWsKLS0tIEQ5NGRITUsxbGp3Vk1aRFlqdTdh
            YXFSN3lPbUdMbkVlTkpqZ2JtTVVjWEkK8wQgxwXqSnQg3mpOdkPlgRC5IY7IYc4U
            0470YmsZqpteF2XFwbpBL7yQQR+NSeQ6D5f9kgEX4IPS1bIJJ+Um4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14fewqugfz73kxscwghlr20avuehy9z0ya2katsyum6gflhcs4e3q5q54yu
    lastmodified: "2026-09-20T21:40:59Z"
    mac: ENC[AES256_GCM,data:fqtp36+nOnKV0lnHVB9SdPNxmTsZYGpzdPJ//hFwh70EPezOvwc/DTRkOiUdBk1SvGwmFbAbVQKPMFB73SNJvewwa2/UP70sRc+g0E+pp4iDfGkO+9r7vehyBiUf0oIiJ1B5JzTRFEOVSGlfvcKsLkOj2JEhBj3Ri7Yc4r1NPu8=,iv:kg9OQn+XoF897wgPkhomGQUsUBs0qTr4GIxNs1zSfMU=,tag:VQvapGFtwXbE/HZ7VGOnKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
